### PR TITLE
adapt to coq/coq#15220

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by JasonGross — CHANGES_REQUESTED** [review]
Instead of replacing these lines in the list, you should add the new lines at the head of the list; the script tries all options in the list to discover the first one that works, so we should keep the old way of doing things around for older versions of Coq.

**Comment by gares** [comment]
Would you mind suggesting the change, I'm not so sure I see what you mean.
Also, the old plugin names now still works *but* emit a warning, this is why I did the overlay in the fist place.
So putting the old names first may not work (it will compile, but fail later I guess).

**Review by JasonGross — CHANGES_REQUESTED** [review]

**Comment by JasonGross** [comment]
The new names should come first.  I've made a suggestion in review

**Comment by gares** [comment]
thanks

**Comment by JasonGross** [comment]
I expect that some of the regexs in some of the test-suite file scripts may need to be changed.  Is this branch enough to get it to pass on the most recent master?

**Pull request merged**
